const c=document.querySelector('#c'),x=c.getContext('2d');let W,H,dpr,joy={x:0,y:0},last=performance.now(),time=60,over=true,mode='normal',character='Finn';
const P={x:0,z:0,y:0,vy:0,stamina:100,sprint:false,slide:false,infected:false,carry:0,parkour:false};let bots=[];
const $=s=>document.querySelector(s),role=$('#role'),timer=$('#timer'),fill=$('#staminaFill'),msg=$('#message'),menu=$('#menu'),modeLabel=$('#modeLabel'),survivors=$('#survivors');
const blocks=[[-7,-5,4,2],[6,3,4,2],[-1,9,6,2],[11,-8,3,3],[-12,6,3,4],[1,-11,5,2]];const inside=(px,pz,b,p=.45)=>px>b[0]-b[2]/2-p&&px<b[0]+b[2]/2+p&&pz>b[1]-b[3]/2-p&&pz<b[1]+b[3]/2+p;
function resize(){dpr=Math.min(devicePixelRatio,2);W=innerWidth;H=innerHeight;c.width=W*dpr;c.height=H*dpr;x.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function reset(m){mode=m;time=m==='zombie'?75:60;over=false;Object.assign(P,{x:0,z:0,y:0,vy:0,stamina:100,infected:false});bots=m==='normal'?[bot(7,-6,true,'TAGGER')]:[bot(8,-7,true,'INFECTED'),bot(-8,-5,false,'GWEN'),bot(8,7,false,'OWEN')];modeLabel.textContent='OFFLINE • '+(m==='normal'?'NORMAL TAG':'ZOMBIE TAG');role.textContent='RUNNER • '+character;menu.classList.add('hidden');msg.classList.remove('show')}
function bot(x,z,infected,name){return{x,z,infected,name,speed:infected?7.78:6.7}}
document.querySelectorAll('[data-char]').forEach(b=>b.onclick=()=>{character=b.dataset.char;document.querySelectorAll('[data-char]').forEach(q=>q.classList.toggle('selected',q===b))});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>reset(b.dataset.mode));
const pad=$('#leftPad'),stick=$('#stick');function joyAt(e){let r=pad.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),m=Math.hypot(dx,dy)||1,k=Math.min(1,52/m);joy={x:dx/m*k,y:dy/m*k};stick.style.transform=`translate(${joy.x*38}px,${joy.y*38}px)`}pad.onpointerdown=e=>{pad.setPointerCapture(e.pointerId);joyAt(e)};pad.onpointermove=e=>{if(pad.hasPointerCapture(e.pointerId))joyAt(e)};pad.onpointerup=pad.onpointercancel=()=>{joy={x:0,y:0};stick.style.transform=''};
function hold(id,key){let b=$(id);b.onpointerdown=e=>{e.preventDefault();P[key]=true;b.classList.add('active');b.setPointerCapture(e.pointerId)};b.onpointerup=b.onpointercancel=()=>{P[key]=false;b.classList.remove('active')}}hold('#sprint','sprint');hold('#slide','slide');
function jump(){if(P.y<=.01){let t=P.stamina/100;P.vy=5.75+(6.7-5.75)*t;P.carry=P.sprint?(6.10+(7.65-6.10)*t):0;P.stamina=Math.max(0,P.stamina-18)}}$('#jump').onpointerdown=e=>{e.currentTarget.classList.add('active');jump()};$('#jump').onpointerup=e=>e.currentTarget.classList.remove('active');$('#parkour').onpointerdown=e=>{e.currentTarget.classList.add('active');P.parkour=true;if(P.y<.7){P.vy=Math.max(P.vy,4.7);P.stamina=Math.max(0,P.stamina-10)}};$('#parkour').onpointerup=e=>{e.currentTarget.classList.remove('active');P.parkour=false};
addEventListener('keydown',e=>{if(e.key==='Shift')P.sprint=true;if(e.code==='Space')jump();if(e.key==='w')joy.y=-1;if(e.key==='s')joy.y=1;if(e.key==='a')joy.x=-1;if(e.key==='d')joy.x=1});addEventListener('keyup',e=>{if(e.key==='Shift')P.sprint=false;if('wasd'.includes(e.key))joy={x:0,y:0}});
function dist(a,b){return Math.hypot(a.x-b.x,a.z-b.z)}function moveToward(a,t,s,dt){let dx=t.x-a.x,dz=t.z-a.z,d=Math.hypot(dx,dz)||1,ox=a.x,oz=a.z;a.x+=dx/d*s*dt;a.z+=dz/d*s*dt;if(blocks.some(b=>inside(a.x,a.z,b,.25))){a.x=ox-dz/d*s*.72*dt;a.z=oz+dx/d*s*.72*dt}}
function update(dt){if(over)return;time-=dt;if(time<=0){time=0;over=true;flash(P.infected?'INFECTED WIN':'RUNNERS SURVIVE');return}let m=Math.min(1,Math.hypot(joy.x,joy.y)),speed=4.8;if(P.sprint&&P.stamina>0&&m){speed=7.4;P.stamina=Math.max(0,P.stamina-22*dt)}else P.stamina=Math.min(100,P.stamina+17*dt);if(P.slide&&m&&P.y<.15)speed*=1.12;if(P.y>.01&&P.carry>speed)speed=P.carry;let ox=P.x,oz=P.z;P.x+=joy.x*speed*dt;P.z+=joy.y*speed*dt;let hit=blocks.find(b=>inside(P.x,P.z,b));if(hit&&P.y<.65){if(P.parkour&&P.stamina>0){P.vy=Math.max(P.vy,5.15);P.stamina=Math.max(0,P.stamina-8);P.x+=joy.x*.55;P.z+=joy.y*.55}else{P.x=ox;P.z=oz}}P.vy-=13.5*dt;P.y=Math.max(0,P.y+P.vy*dt);if(P.y===0&&P.vy<0){P.vy=0;P.carry=0}
for(const b of bots){if(b.infected){let targets=[...bots.filter(q=>!q.infected),...(!P.infected?[P]:[])];if(targets.length){let t=targets.reduce((a,q)=>dist(b,q)<dist(b,a)?q:a,targets[0]);moveToward(b,t,b.speed,dt);if(dist(b,t)<.78){if(t===P){P.infected=true;role.textContent='INFECTED • '+character;flash('YOU WERE INFECTED')}else{t.infected=true;t.speed=7.78;t.name='INFECTED'}}}}else{let threat=bots.filter(q=>q.infected).sort((a,q)=>dist(b,a)-dist(b,q))[0];if(threat){let dx=b.x-threat.x,dz=b.z-threat.z,d=Math.hypot(dx,dz)||1;b.x+=dx/d*b.speed*dt;b.z+=dz/d*b.speed*dt}}}
if(mode==='normal'&&P.infected){over=true;flash('TAGGED!')}if(mode==='zombie'&&P.infected&&bots.every(b=>b.infected)){over=true;flash('EVERYONE INFECTED')}}
function flash(t){msg.textContent=t;msg.classList.add('show');setTimeout(()=>{if(!over)msg.classList.remove('show')},1100)}
// Isometric camera: three-dimensional-looking geometry without a network dependency.
function proj(wx,wz,wy=0){const sc=Math.min(W/35,H/24);let dx=wx-P.x,dz=wz-P.z;return[W*.5+(dx-dz)*sc*.82,H*.56+(dx+dz)*sc*.39-wy*sc*1.25]}
function polygon(points,color,stroke='#ffffff22'){x.beginPath();points.forEach((p,i)=>i?x.lineTo(...p):x.moveTo(...p));x.closePath();x.fillStyle=color;x.fill();x.strokeStyle=stroke;x.stroke()}
function cube(cx,cz,w,d,h){const a=proj(cx-w/2,cz-d/2),b=proj(cx+w/2,cz-d/2),c=proj(cx+w/2,cz+d/2),e=proj(cx-w/2,cz+d/2),at=proj(cx-w/2,cz-d/2,h),bt=proj(cx+w/2,cz-d/2,h),ct=proj(cx+w/2,cz+d/2,h),et=proj(cx-w/2,cz+d/2,h);polygon([e,c,ct,et],'#253746');polygon([b,c,ct,bt],'#344a5a');polygon([at,bt,ct,et],'#496171')}
function avatar(a,name,color){const p=proj(a.x,a.z,a.y||0),sc=Math.min(W/35,H/24),slide=a.slide&&a.y<.15;let head=slide?sc*.35:sc*.9;x.fillStyle='#0005';x.beginPath();x.ellipse(p[0],p[1]+3,sc*.43,sc*.17,0,0,7);x.fill();x.strokeStyle=color;x.lineWidth=Math.max(3,sc*.22);x.lineCap='round';x.beginPath();x.moveTo(p[0],p[1]-head);x.lineTo(p[0],p[1]-sc*.3);x.stroke();x.fillStyle=color;x.beginPath();x.arc(p[0],p[1]-head-sc*.17,sc*.21,0,7);x.fill();x.fillStyle='#fff';x.font='bold 9px Arial';x.textAlign='center';x.fillText(name,p[0],p[1]-head-sc*.5)}
function draw(){x.clearRect(0,0,W,H);let g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,'#233b51');g.addColorStop(1,'#0b151e');x.fillStyle=g;x.fillRect(0,0,W,H);let floor=[proj(-40,-40),proj(40,-40),proj(40,40),proj(-40,40)];polygon(floor,'#17252e','#17252e');x.strokeStyle='#ffffff10';x.lineWidth=1;for(let i=-30;i<=30;i+=3){let a=proj(i,-30),b=proj(i,30);x.beginPath();x.moveTo(...a);x.lineTo(...b);x.stroke();a=proj(-30,i);b=proj(30,i);x.beginPath();x.moveTo(...a);x.lineTo(...b);x.stroke()}let objects=blocks.map(b=>({depth:b[0]+b[1],draw:()=>cube(b[0],b[1],b[2],b[3],1.3)}));for(const bot of bots)objects.push({depth:bot.x+bot.z,draw:()=>avatar(bot,bot.name,bot.infected?'#ff604c':'#ffd166')});objects.push({depth:P.x+P.z,draw:()=>avatar(P,character,P.infected?'#ff604c':'#64c9ff')});objects.sort((a,b)=>a.depth-b.depth).forEach(o=>o.draw());timer.textContent=Math.ceil(time);fill.style.width=P.stamina+'%';fill.classList.toggle('low',P.stamina<25);survivors.textContent=mode==='zombie'?'RUNNERS LEFT: '+(bots.filter(b=>!b.infected).length+(!P.infected?1:0)):''}
function loop(t){let dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);