const c=document.querySelector('#c'),x=c.getContext('2d');let W,H,dpr,joy={x:0,y:0},last=performance.now(),time=60,over=true,mode='normal',character='Finn',arena='training';
const P={x:0,z:0,y:0,vy:0,stamina:100,sprint:false,slide:false,infected:false,carry:0,parkour:false};let bots=[];let paused=false;let facing=0,camYaw=0,camOrbit=0,lookPointer=null,lookX=0;
const $=s=>document.querySelector(s),role=$('#role'),timer=$('#timer'),fill=$('#staminaFill'),msg=$('#message'),menu=$('#menu'),modeLabel=$('#modeLabel'),survivors=$('#survivors');
const ARENAS={training:[[-7,-5,4,2],[6,3,4,2],[-1,9,6,2],[11,-8,3,3],[-12,6,3,4],[1,-11,5,2],[-15,-12,7,2],[15,12,7,2],[-15,12,3,6],[15,-12,3,6],[-5,15,5,2],[7,-15,5,2]],yard:[[-10,-7,7,2],[0,-7,5,2],[9,-4,3,7],[-8,5,3,7],[1,6,8,2],[11,8,4,3]],rooftops:[[-10,-8,8,5],[2,-8,7,4],[10,-2,5,7],[-8,5,6,5],[2,5,5,4],[10,8,5,4]]};let blocks=ARENAS.training;const inside=(px,pz,b,p=.45)=>px>b[0]-b[2]/2-p&&px<b[0]+b[2]/2+p&&pz>b[1]-b[3]/2-p&&pz<b[1]+b[3]/2+p;
function resize(){dpr=Math.min(devicePixelRatio,2);W=innerWidth;H=innerHeight;c.width=W*dpr;c.height=H*dpr;x.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
// Drag empty gameplay space to orbit the camera. Controls stop propagation before reaching the canvas.
c.addEventListener('pointerdown',e=>{lookPointer=e.pointerId;lookX=e.clientX;c.setPointerCapture(e.pointerId)});c.addEventListener('pointermove',e=>{if(e.pointerId!==lookPointer)return;camOrbit+=(e.clientX-lookX)*.0027;lookX=e.clientX});const endLook=e=>{if(e.pointerId===lookPointer)lookPointer=null};c.addEventListener('pointerup',endLook);c.addEventListener('pointercancel',endLook);
function reset(m){mode=m;paused=false;$('#pauseMenu').classList.add('hidden');$('#pause').textContent='Ⅱ';$('#pause').classList.remove('active');time=m==='zombie'?75:60;over=false;Object.assign(P,{x:0,z:0,y:0,vy:0,stamina:100,infected:false,carry:0,sprint:false,slide:false,parkour:false});bots=m==='normal'?[bot(7,-6,true,'TAGGER')]:[bot(8,-7,true,'INFECTED'),bot(-8,-5,false,'GWEN'),bot(8,7,false,'OWEN')];modeLabel.textContent='OFFLINE • '+(m==='normal'?'NORMAL TAG':'ZOMBIE TAG')+' • '+arena.replace('training','TRAINING GROUNDS').replace('yard','THE YARD').replace('rooftops','ROOFTOPS').toUpperCase();role.textContent='RUNNER • 3D TEST';menu.classList.add('hidden');msg.classList.remove('show')}
function bot(x,z,infected,name){return{x,z,infected,name,speed:infected?7.15:6.35}}
document.querySelectorAll('[data-arena]').forEach(b=>b.onclick=()=>{arena=b.dataset.arena;blocks=ARENAS[arena];document.querySelectorAll('[data-arena]').forEach(q=>q.classList.toggle('selected',q===b))});document.querySelectorAll('[data-char]').forEach(b=>b.onclick=()=>{character=b.dataset.char;document.querySelectorAll('[data-char]').forEach(q=>q.classList.toggle('selected',q===b))});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>reset(b.dataset.mode));
const pad=$('#leftPad'),stick=$('#stick');function joyAt(e){let r=pad.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),m=Math.hypot(dx,dy)||1,k=Math.min(1,52/m);joy={x:dx/m*k,y:dy/m*k};stick.style.transform=`translate(${joy.x*38}px,${joy.y*38}px)`}pad.onpointerdown=e=>{pad.setPointerCapture(e.pointerId);joyAt(e)};pad.onpointermove=e=>{if(pad.hasPointerCapture(e.pointerId))joyAt(e)};pad.onpointerup=pad.onpointercancel=()=>{joy={x:0,y:0};stick.style.transform=''};
function hold(id,key){let b=$(id);b.onpointerdown=e=>{e.preventDefault();P[key]=true;b.classList.add('active');b.setPointerCapture(e.pointerId)};b.onpointerup=b.onpointercancel=()=>{P[key]=false;b.classList.remove('active')}}hold('#sprint','sprint');hold('#slide','slide');
function jump(){if(P.y<=.01){let t=P.stamina/100;P.vy=5.75+(6.7-5.75)*t;P.carry=P.sprint?(6.10+(7.65-6.10)*t):0;P.stamina=Math.max(0,P.stamina-18)}}$('#jump').onpointerdown=e=>{e.currentTarget.classList.add('active');jump()};$('#jump').onpointerup=e=>e.currentTarget.classList.remove('active');$('#parkour').onpointerdown=e=>{e.currentTarget.classList.add('active');P.parkour=true;if(P.y<.7){P.vy=Math.max(P.vy,4.7);P.stamina=Math.max(0,P.stamina-10)}};$('#parkour').onpointerup=e=>{e.currentTarget.classList.remove('active');P.parkour=false};
addEventListener('keydown',e=>{if(e.key==='Shift')P.sprint=true;if(e.code==='Space')jump();if(e.key==='w')joy.y=-1;if(e.key==='s')joy.y=1;if(e.key==='a')joy.x=-1;if(e.key==='d')joy.x=1});addEventListener('keyup',e=>{if(e.key==='Shift')P.sprint=false;if('wasd'.includes(e.key))joy={x:0,y:0}});
function dist(a,b){return Math.hypot(a.x-b.x,a.z-b.z)}function moveToward(a,t,s,dt){let dx=t.x-a.x,dz=t.z-a.z,d=Math.hypot(dx,dz)||1,ox=a.x,oz=a.z;a.x+=dx/d*s*dt;a.z+=dz/d*s*dt;if(blocks.some(b=>inside(a.x,a.z,b,.25))){a.x=ox-dz/d*s*.72*dt;a.z=oz+dx/d*s*.72*dt}}
function update(dt){if(over||paused)return;time-=dt;if(time<=0){time=0;over=true;flash(P.infected?'INFECTED WIN':'RUNNERS SURVIVE');return}let m=Math.min(1,Math.hypot(joy.x,joy.y)),speed=4.8;if(P.sprint&&P.stamina>0&&m){speed=7.4;P.stamina=Math.max(0,P.stamina-22*dt)}else P.stamina=Math.min(100,P.stamina+17*dt);if(P.slide&&m&&P.y<.15)speed*=1.12;if(P.y>.01&&P.carry>speed)speed=P.carry;let ox=P.x,oz=P.z;P.x+=joy.x*speed*dt;P.z+=joy.y*speed*dt;if(m>.08)facing=Math.atan2(joy.x,-joy.y);let hit=blocks.find(b=>inside(P.x,P.z,b));if(hit&&P.y<.65){if(P.parkour&&P.stamina>0){P.vy=Math.max(P.vy,5.15);P.stamina=Math.max(0,P.stamina-8);P.x+=joy.x*.55;P.z+=joy.y*.55}else{P.x=ox;P.z=oz}}P.vy-=13.5*dt;P.y=Math.max(0,P.y+P.vy*dt);if(P.y===0&&P.vy<0){P.vy=0;P.carry=0}
for(const b of bots){if(b.infected){let targets=[...bots.filter(q=>!q.infected),...(!P.infected?[P]:[])];if(targets.length){let t=targets.reduce((a,q)=>dist(b,q)<dist(b,a)?q:a,targets[0]);moveToward(b,t,b.speed,dt);if(dist(b,t)<.78){if(t===P){P.infected=true;role.textContent='INFECTED • '+character;flash('YOU WERE INFECTED')}else{t.infected=true;t.speed=7.78;t.name='INFECTED'}}}}else{let threat=bots.filter(q=>q.infected).sort((a,q)=>dist(b,a)-dist(b,q))[0];if(threat){let dx=b.x-threat.x,dz=b.z-threat.z,d=Math.hypot(dx,dz)||1;b.x+=dx/d*b.speed*dt;b.z+=dz/d*b.speed*dt}}}
if(mode==='normal'&&P.infected){over=true;flash('TAGGED!')}if(mode==='zombie'&&P.infected&&bots.every(b=>b.infected)){over=true;flash('EVERYONE INFECTED')}}
function flash(t){msg.textContent=t;msg.classList.add('show');setTimeout(()=>{if(!over)msg.classList.remove('show')},1100)}
// Low third-person chase camera. This changes presentation only; world-space movement,
// collision, stamina, parkour and bot tuning remain untouched.
function angleLerp(a,b,t){let d=((b-a+Math.PI)%(Math.PI*2)+Math.PI*2)%(Math.PI*2)-Math.PI;return a+d*t}
function proj(wx,wz,wy=0){
  const targetYaw=facing+camOrbit;camYaw=angleLerp(camYaw,targetYaw,.09);
  const fx=Math.sin(camYaw),fz=-Math.cos(camYaw),rx=Math.cos(camYaw),rz=Math.sin(camYaw);
  const camX=P.x-fx*6.4,camZ=P.z-fz*6.4,camY=3.15;
  const dx=wx-camX,dz=wz-camZ,dy=wy-camY;
  const cx=dx*rx+dz*rz,forward=dx*fx+dz*fz;
  // Camera pitches slightly downward toward a point just above/ahead of the runner.
  const pitch=-.145,cp=Math.cos(pitch),sp=Math.sin(pitch);
  const cy=dy*cp-forward*sp,cz=forward*cp+dy*sp;
  const near=Math.max(.35,cz),f=(H*.88)/Math.tan(64*Math.PI/360);
  return[W*.5+cx*f/near,H*.49-cy*f/near]
}
function polygon(points,color){x.fillStyle=color;x.beginPath();x.moveTo(...points[0]);for(let i=1;i<points.length;i++)x.lineTo(...points[i]);x.closePath();x.fill()}
function box3d(b){let[a,z,w,d]=b,h=1.7,tl=proj(a-w/2,z-d/2,h),tr=proj(a+w/2,z-d/2,h),br=proj(a+w/2,z+d/2,h),bl=proj(a-w/2,z+d/2,h),fl=proj(a-w/2,z+d/2,0),fr=proj(a+w/2,z+d/2,0),rr=proj(a+w/2,z-d/2,0);polygon([bl,br,fr,fl],'#8b9087');polygon([tr,br,fr,rr],'#777d75');polygon([tl,tr,br,bl],'#b9bdb3');x.strokeStyle='#52585055';x.beginPath();x.moveTo(...tl);x.lineTo(...tr);x.lineTo(...br);x.lineTo(...bl);x.closePath();x.stroke()}
function person(a,color,label,isPlayer=false){let y=a.y||0,feet=proj(a.x,a.z,y),hip=proj(a.x,a.z,y+.65),chest=proj(a.x,a.z,y+1.15),head=proj(a.x,a.z,y+1.58),sc=Math.max(8,Math.min(W,H)/34),skin=isPlayer?'#9b694d':'#a87556';x.fillStyle='#0003';x.beginPath();x.ellipse(feet[0],feet[1]+3,sc*.62,sc*.2,0,0,7);x.fill();x.strokeStyle='#171b20';x.lineWidth=sc*.28;x.lineCap='round';x.beginPath();x.moveTo(hip[0]-sc*.12,hip[1]);x.lineTo(feet[0]-sc*.28,feet[1]);x.moveTo(hip[0]+sc*.12,hip[1]);x.lineTo(feet[0]+sc*.28,feet[1]);x.stroke();x.strokeStyle=isPlayer?'#172b3d':color;x.lineWidth=sc*.62;x.beginPath();x.moveTo(hip[0],hip[1]);x.lineTo(chest[0],chest[1]);x.stroke();x.strokeStyle='#20262b';x.lineWidth=sc*.22;x.beginPath();x.moveTo(chest[0]-sc*.18,chest[1]+sc*.1);x.lineTo(hip[0]-sc*.55,hip[1]+sc*.18);x.moveTo(chest[0]+sc*.18,chest[1]+sc*.1);x.lineTo(hip[0]+sc*.55,hip[1]+sc*.18);x.stroke();x.fillStyle=skin;x.beginPath();x.arc(head[0],head[1],sc*.31,0,7);x.fill();if(isPlayer){let rel=Math.cos(facing-(camYaw+camOrbit));if(rel>0){x.fillStyle='#0b1720';x.fillRect(chest[0]-sc*.16,chest[1]-sc*.03,sc*.32,sc*.30);x.fillStyle='#314e62';x.fillRect(chest[0]-sc*.11,chest[1]+sc*.02,sc*.22,sc*.08)}else{x.fillStyle='#d6dadd';x.beginPath();x.arc(head[0]-sc*.10,head[1]-sc*.03,sc*.035,0,7);x.arc(head[0]+sc*.10,head[1]-sc*.03,sc*.035,0,7);x.fill();x.strokeStyle='#573b31';x.lineWidth=1.5;x.beginPath();x.moveTo(head[0]-sc*.10,head[1]+sc*.10);x.quadraticCurveTo(head[0],head[1]+sc*.16,head[0]+sc*.10,head[1]+sc*.10);x.stroke()}}else{x.fillStyle='#26333b';x.font='bold 9px Arial';x.textAlign='center';x.fillText(label,head[0],head[1]-sc*.55)}}
function draw(){x.clearRect(0,0,W,H);let sky=x.createLinearGradient(0,0,0,H*.62);sky.addColorStop(0,'#c9d8dd');sky.addColorStop(1,'#e6ece9');x.fillStyle=sky;x.fillRect(0,0,W,H);let floor=[proj(-42,-42),proj(42,-42),proj(42,42),proj(-42,42)];polygon(floor,'#aab4aa');x.strokeStyle='#ffffff25';x.lineWidth=1;for(let i=-36;i<=36;i+=4){let a=proj(i,-36),b=proj(i,36);x.beginPath();x.moveTo(...a);x.lineTo(...b);x.stroke();a=proj(-36,i);b=proj(36,i);x.beginPath();x.moveTo(...a);x.lineTo(...b);x.stroke()}const items=[...blocks.map(b=>({depth:b[0]+b[1],kind:'block',b})),...bots.map(b=>({depth:b.x+b.z,kind:'bot',b})),{depth:P.x+P.z,kind:'player',b:P}];items.sort((a,b)=>a.depth-b.depth);for(const item of items){if(item.kind==='block')box3d(item.b);else if(item.kind==='bot')person(item.b,item.b.infected?'#9d3e32':'#b89b52',item.b.name);else person(P,P.infected?'#8d332d':'#20394e',character.toUpperCase(),true)}timer.textContent='ROUND 1/3 • 0:'+String(Math.ceil(time)).padStart(2,'0');fill.style.width=P.stamina+'%';fill.classList.toggle('low',P.stamina<25);let alive=bots.filter(b=>!b.infected).length+(!P.infected?1:0);survivors.textContent=mode==='zombie'?'RUNNERS LEFT: '+alive:'TRAINING GROUNDS • CHASE QUAD'}
function setPaused(v){paused=v;$('#pauseMenu').classList.toggle('hidden',!v);$('#pause').textContent=v?'▶':'Ⅱ';$('#pause').classList.toggle('active',v)}$('#pause').onpointerdown=e=>{e.preventDefault();e.stopPropagation();setPaused(!paused)};$('#resumeGame').onclick=()=>setPaused(false);$('#restartGame').onclick=()=>reset(mode);$('#mainMenu').onclick=()=>{setPaused(false);over=true;joy={x:0,y:0};P.sprint=false;P.slide=false;P.parkour=false;menu.classList.remove('hidden')};
function loop(t){let dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);