const c=document.querySelector('#c'),x=c.getContext('2d');let W,H,dpr,joy={x:0,y:0},last=performance.now(),time=60,over=true,mode='normal',character='Finn';
const P={x:0,z:0,y:0,vy:0,stamina:100,sprint:false,slide:false,infected:false};let bots=[];
const $=s=>document.querySelector(s),role=$('#role'),timer=$('#timer'),fill=$('#staminaFill'),msg=$('#message'),menu=$('#menu'),modeLabel=$('#modeLabel'),survivors=$('#survivors');
const blocks=[[-7,-5,4,2],[6,3,4,2],[-1,9,6,2],[11,-8,3,3],[-12,6,3,4],[1,-11,5,2]];
function resize(){dpr=Math.min(devicePixelRatio,2);W=innerWidth;H=innerHeight;c.width=W*dpr;c.height=H*dpr;x.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
function reset(m){mode=m;time=m==='zombie'?75:60;over=false;Object.assign(P,{x:0,z:0,y:0,vy:0,stamina:100,infected:false});bots=m==='normal'?[bot(7,-6,true,'TAGGER')]:[bot(8,-7,true,'INFECTED'),bot(-8,-5,false,'GWEN'),bot(8,7,false,'OWEN')];modeLabel.textContent='OFFLINE • '+(m==='normal'?'NORMAL TAG':'ZOMBIE TAG');role.textContent='RUNNER • '+character;menu.classList.add('hidden');msg.classList.remove('show')}
function bot(x,z,infected,name){return{x,z,infected,name,speed:infected?7.78:6.7}}
document.querySelectorAll('[data-char]').forEach(b=>b.onclick=()=>{character=b.dataset.char;document.querySelectorAll('[data-char]').forEach(q=>q.classList.toggle('selected',q===b))});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>reset(b.dataset.mode));
const pad=$('#leftPad'),stick=$('#stick');function joyAt(e){let r=pad.getBoundingClientRect(),dx=e.clientX-(r.left+r.width/2),dy=e.clientY-(r.top+r.height/2),m=Math.hypot(dx,dy)||1,k=Math.min(1,52/m);joy={x:dx/m*k,y:dy/m*k};stick.style.transform=`translate(${joy.x*38}px,${joy.y*38}px)`}pad.onpointerdown=e=>{pad.setPointerCapture(e.pointerId);joyAt(e)};pad.onpointermove=e=>{if(pad.hasPointerCapture(e.pointerId))joyAt(e)};pad.onpointerup=pad.onpointercancel=()=>{joy={x:0,y:0};stick.style.transform=''};
function hold(id,key){let b=$(id);b.onpointerdown=e=>{e.preventDefault();P[key]=true;b.classList.add('active');b.setPointerCapture(e.pointerId)};b.onpointerup=b.onpointercancel=()=>{P[key]=false;b.classList.remove('active')}}hold('#sprint','sprint');hold('#slide','slide');
function jump(){if(P.y<=.01){let t=P.stamina/100;P.vy=5.75+(6.7-5.75)*t;P.stamina=Math.max(0,P.stamina-18)}}$('#jump').onpointerdown=e=>{e.currentTarget.classList.add('active');jump()};$('#jump').onpointerup=e=>e.currentTarget.classList.remove('active');$('#parkour').onpointerdown=e=>{e.currentTarget.classList.add('active');if(P.y<.7){P.vy=Math.max(P.vy,4.7);P.stamina=Math.max(0,P.stamina-10)}};$('#parkour').onpointerup=e=>e.currentTarget.classList.remove('active');
addEventListener('keydown',e=>{if(e.key==='Shift')P.sprint=true;if(e.code==='Space')jump();if(e.key==='w')joy.y=-1;if(e.key==='s')joy.y=1;if(e.key==='a')joy.x=-1;if(e.key==='d')joy.x=1});addEventListener('keyup',e=>{if(e.key==='Shift')P.sprint=false;if('wasd'.includes(e.key))joy={x:0,y:0}});
function dist(a,b){return Math.hypot(a.x-b.x,a.z-b.z)}function moveToward(a,t,s,dt){let dx=t.x-a.x,dz=t.z-a.z,d=Math.hypot(dx,dz)||1;a.x+=dx/d*s*dt;a.z+=dz/d*s*dt}
function update(dt){if(over)return;time-=dt;if(time<=0){time=0;over=true;flash(P.infected?'INFECTED WIN':'RUNNERS SURVIVE');return}let m=Math.min(1,Math.hypot(joy.x,joy.y)),speed=4.8;if(P.sprint&&P.stamina>0&&m){speed=7.4;P.stamina=Math.max(0,P.stamina-22*dt)}else P.stamina=Math.min(100,P.stamina+17*dt);if(P.slide&&m)speed*=1.08;P.x+=joy.x*speed*dt;P.z+=joy.y*speed*dt;P.vy-=13.5*dt;P.y=Math.max(0,P.y+P.vy*dt);if(P.y===0&&P.vy<0)P.vy=0;
for(const b of bots){if(b.infected){let targets=[...bots.filter(q=>!q.infected),...(!P.infected?[P]:[])];if(targets.length){let t=targets.reduce((a,q)=>dist(b,q)<dist(b,a)?q:a,targets[0]);moveToward(b,t,b.speed,dt);if(dist(b,t)<.78){if(t===P){P.infected=true;role.textContent='INFECTED • '+character;flash('YOU WERE INFECTED')}else{t.infected=true;t.speed=7.78;t.name='INFECTED'}}}}else{let threat=bots.filter(q=>q.infected).sort((a,q)=>dist(b,a)-dist(b,q))[0];if(threat){let dx=b.x-threat.x,dz=b.z-threat.z,d=Math.hypot(dx,dz)||1;b.x+=dx/d*b.speed*dt;b.z+=dz/d*b.speed*dt}}}
if(mode==='normal'&&P.infected){over=true;flash('TAGGED!')}if(mode==='zombie'&&P.infected&&bots.every(b=>b.infected)){over=true;flash('EVERYONE INFECTED')}}
function flash(t){msg.textContent=t;msg.classList.add('show');setTimeout(()=>{if(!over)msg.classList.remove('show')},1100)}
function proj(wx,wz,wy=0){let s=Math.min(W,H)/28;return[W/2+(wx-P.x)*s,H/2+(wz-P.z)*s-wy*s]}
function draw(){x.clearRect(0,0,W,H);let g=x.createLinearGradient(0,0,0,H);g.addColorStop(0,'#182633');g.addColorStop(1,'#0a1015');x.fillStyle=g;x.fillRect(0,0,W,H);let s=Math.min(W,H)/28;x.strokeStyle='#ffffff0c';for(let i=-30;i<=30;i++){let a=proj(i,-30),b=proj(i,30);x.beginPath();x.moveTo(...a);x.lineTo(...b);x.stroke();a=proj(-30,i);b=proj(30,i);x.beginPath();x.moveTo(...a);x.lineTo(...b);x.stroke()}for(const[bz1,bz2,bw,bh]of blocks){let q=proj(bz1,bz2);x.fillStyle='#293946';x.fillRect(q[0]-bw*s/2,q[1]-bh*s/2,bw*s,bh*s)}for(const b of bots){let p=proj(b.x,b.z);x.fillStyle=b.infected?'#ff604c':'#ffd166';x.beginPath();x.arc(p[0],p[1],11,0,7);x.fill();x.fillStyle='#fff';x.font='bold 9px Arial';x.textAlign='center';x.fillText(b.name,p[0],p[1]-16)}let pp=proj(P.x,P.z,P.y);x.fillStyle=P.infected?'#ff604c':'#64c9ff';x.beginPath();x.arc(pp[0],pp[1],12,0,7);x.fill();timer.textContent=Math.ceil(time);fill.style.width=P.stamina+'%';fill.classList.toggle('low',P.stamina<25);let alive=bots.filter(b=>!b.infected).length+(!P.infected?1:0);survivors.textContent=mode==='zombie'?'RUNNERS LEFT: '+alive:''}
function loop(t){let dt=Math.min(.033,(t-last)/1000);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);